#!/usr/bin/env ruby

raise ArgumentError, 'Usage: cmd [api_key] [keyword]' unless ARGV.length == 2

require 'rubygems'
require 'bundler'
Bundler.setup(:default)

require_relative '../lib/weito'

Weito.api_key = ARGV[0].to_s
keyword = ARGV[1].to_s

p "Searching for #{keyword} with api key #{Weito.api_key} ..."
p Weito.search(keyword)
